[package]

name = "shp"
version = "0.0.1"
authors = [ "Nick Quaranto <nick@quaran.to>" ]

[[bin]]

name = "shp"

[dependencies.git2]
git = "https://github.com/alexcrichton/git2-rs"

[dependencies]
getopts = "0.1.4"